name: Update README stats
on:
push:
paths:
- '**.py'
- '**.js'
- '**.java'
- '**.ts'
- '8-kyu/**'
- '7-kyu/**'
- '6-kyu/**'
- '5-kyu/**'
- '4-kyu/**'
- '3-kyu/**'
- '2-kyu/**'
- '1-kyu/**'
schedule:
- cron: '0 6 * * 1' # every Monday 06:00 UTC


jobs:
update:
runs-on: ubuntu-latest
permissions:
contents: write
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
with:
python-version: '3.12'
- name: Update README
run: python scripts/update_readme.py
- name: Commit changes
run: |
if [[ -n "$(git status --porcelain)" ]]; then
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add README.md
git commit -m "chore(stats): auto-update README counters"
git push
fi